import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import {
  ChevronLeft,
  AlarmClock,
  FileQuestion,
  Trophy,
  History,
  ArrowRight,
} from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getCurrentProfile } from "@/lib/session";
import { canAccessCourse } from "@/lib/data/courses";
import { getMockTests } from "@/lib/data/mock-tests";
import { getAiKeyStatus } from "@/lib/ai/keys";
import { GenerateMockDialog } from "@/components/mock-tests/generate-mock-dialog";
import { DeleteMockButton } from "@/components/mock-tests/delete-mock-button";
import { Stagger, StaggerItem } from "@/components/motion/motion";

export const dynamic = "force-dynamic";

export default async function MockTestsPage({
  params,
}: {
  params: Promise<{ courseSlug: string }>;
}) {
  const { courseSlug } = await params;
  const profile = await getCurrentProfile();
  if (!profile) redirect("/sign-in");

  const course = await prisma.course.findUnique({ where: { slug: courseSlug } });
  if (!course || !canAccessCourse(course, profile.id)) notFound();

  const [tests, keyStatus] = await Promise.all([
    getMockTests(course.id, profile.id),
    getAiKeyStatus(profile.id),
  ]);

  return (
    <div className="space-y-6">
      <Link
        href="/practice"
        className="inline-flex items-center gap-1 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ChevronLeft className="h-4 w-4" />
        Practice
      </Link>

      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Mock Tests</h1>
          <p className="text-sm text-muted-foreground">
            {course.title} — timed, exam-style tests generated by AI just for you.
          </p>
        </div>
        <GenerateMockDialog
          courseId={course.id}
          courseSlug={course.slug}
          hasAiKey={keyStatus.configured}
        />
      </div>

      {tests.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-border/60 bg-card/50 p-10 text-center">
          <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-primary/10">
            <AlarmClock className="h-7 w-7 text-primary" />
          </div>
          <p className="font-medium text-foreground">No mock tests yet</p>
          <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">
            Generate a timed exam from everything this course covers. You&apos;ll get a score
            report with a per-topic breakdown to target your weak spots.
          </p>
        </div>
      ) : (
        <Stagger className="grid gap-4">
          {tests.map((test) => (
            <StaggerItem
              key={test.id}
              className="rounded-xl border border-border/50 bg-card p-5"
            >
              <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div className="flex items-start gap-4">
                  <div className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-lg border border-primary/20 bg-primary/10">
                    <AlarmClock className="h-5 w-5 text-primary" />
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-semibold text-foreground">{test.title}</h3>
                    <p className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <FileQuestion className="h-3.5 w-3.5" />
                        {test.questionCount} questions
                      </span>
                      <span>{test.durationMinutes} min</span>
                      <span className="capitalize">{test.difficulty}</span>
                    </p>
                    {test.attemptCount > 0 && (
                      <div className="flex flex-wrap items-center gap-1.5 pt-0.5">
                        <span className="inline-flex items-center gap-1 rounded-full border border-np-orange/30 bg-np-orange/10 px-2 py-0.5 text-[11px] font-medium text-np-orange">
                          <Trophy className="h-3 w-3" />
                          Best {test.bestScore}%
                        </span>
                        <span className="rounded-full border border-border/60 bg-secondary px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                          {test.attemptCount} attempt{test.attemptCount === 1 ? "" : "s"}
                        </span>
                      </div>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {test.lastAttemptId && (
                    <Link
                      href={`/practice/${course.slug}/mocks/${test.id}/attempts/${test.lastAttemptId}`}
                      className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-secondary"
                    >
                      <History className="h-4 w-4" />
                      Last result
                    </Link>
                  )}
                  <Link
                    href={`/practice/${course.slug}/mocks/${test.id}`}
                    className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition-all hover:opacity-90"
                  >
                    {test.attemptCount > 0 ? "Retake" : "Take test"}
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                  <DeleteMockButton testId={test.id} />
                </div>
              </div>
            </StaggerItem>
          ))}
        </Stagger>
      )}
    </div>
  );
}
